# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getDXFData <- function(file, prefix, scale) {
    .Call('_dxfspatial_getDXFData', PACKAGE = 'dxfspatial', file, prefix, scale)
}

